Feature: Type-driven config schema — annotated example, JSON schema, per-language sections

  The crap.toml config schema is a single annotated Rust type. From that
  one type, three artifacts derive: the field documentation visible on
  docs.rs / IDE hovers, an exhaustive annotated `crap.example.toml`
  generated by `init`, and a JSON Schema for editor `$schema`
  autocomplete. The schema also grows per-language `[language.<name>]`
  sections (each adapter reads its own) and `[output].title`/`subtitle`
  to label the scorecard.

  These scenarios pin the user-facing contract for #347 (generated
  example + sync guard) and #348 (multi-language schema + output
  title/subtitle). They are the foundation #346 (CI consumes config)
  later sits on top of.

  # Wiring for these scenarios is deferred to the #169 BDD-wiring
  # umbrella, matching config_discovery.feature (#345) and
  # multi_root_src.feature (#336). The behaviors are verified during
  # build by crap-core unit/integration tests (the sync, round-trip, and
  # doc-completeness guards) plus assert_cmd `init` integration tests.
  # crap4ts scenarios are unwireable in this crap4rs harness
  # (`CARGO_BIN_EXE_crap4ts` is set only for same-package binaries) and
  # are verified by a `crates/crap4ts/tests/` integration test — the same
  # constraint noted in config_discovery.feature and cli_init.feature.

  # ── The generated exhaustive example (#347) ────────────────────────

  @unwired
  Scenario: init writes an exhaustive annotated config covering every field
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core sync test + assert_cmd init integration
    Given an empty project directory
    When the operator runs `crap4rs init`
    Then the written config documents every supported field with a leading comment
    And the comment above each field is that field's own schema documentation
    And the mutually-exclusive "preset" and "threshold" are documented with exactly one set live and the other shown as a commented alternative
    And the written config parses back without error

  @unwired
  Scenario: the committed crap.example.toml is byte-identical to init output
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core byte-identity sync test
    Given the repository's committed "crap.example.toml"
    When the example config is regenerated from the schema type
    Then the committed file is byte-identical to the regenerated output
    And a drift between them fails the build with a message naming the regenerate command

  @unwired
  Scenario: the exhaustive example is distinct from the loaded crap.toml
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core test asserting the tool never loads crap.example.toml
    Given the repository's committed "crap.example.toml"
    And the repository's real "crap.toml" dogfood config
    When the analyzer discovers its config in the working directory
    Then the analyzer loads "crap.toml" and never "crap.example.toml"
    And "crap.example.toml" exists purely as the annotated option reference

  # ── Round-trip + completeness guards (#347) ────────────────────────

  @unwired
  Scenario: the generated example sets every optional field and fills every collection
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core round-trip test (every Option=Some except one of preset/threshold, collections non-empty, recursively)
    Given the generated exhaustive example config
    When it is parsed into the config schema
    Then every optional field resolves to a present value, except exactly one of "preset" or "threshold" is set because they are mutually exclusive
    And every collection field is non-empty
    And the parse is not asserted to equal the schema's default value

  @unwired
  Scenario: adding a schema field without wiring it into the generator fails to compile
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via the no-`..` exhaustive destructure compile guard in render_example_config
    Given the config schema type gains a new field
    And the example generator is not updated to emit that field
    When the crate is compiled
    Then compilation fails because the generator's destructure is not exhaustive

  @unwired
  Scenario: every documented field's prose reaches the generated example
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core doc-completeness test
    Given a config field carrying schema documentation
    When the exhaustive example is generated
    Then that field's documentation prose appears as a comment in the output

  # ── Per-language sections (#348) ───────────────────────────────────

  @unwired
  Scenario: each adapter reads its own language section alongside shared defaults
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core per-language merge unit tests
    Given a "crap.toml" with a shared top-level "threshold = 20.0"
    And a "[language.rust]" section with "threshold = 8.0"
    And a "[language.typescript]" section with "threshold = 25.0"
    When the operator runs crap4rs analysis in that directory
    Then the effective threshold is 8.0
    And the typescript section is ignored by crap4rs

  @unwired
  Scenario: a per-language value overrides the shared top-level value
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core precedence unit tests
    Given a "crap.toml" with a shared top-level "threshold = 20.0"
    And a "[language.rust]" section with "threshold = 8.0"
    When the operator runs crap4rs analysis in that directory
    Then the per-language value wins over the shared top-level value
    And the effective threshold is 8.0

  @unwired
  Scenario: a shared top-level value applies when the language section omits it
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core precedence unit tests
    Given a "crap.toml" with a shared top-level "threshold = 20.0"
    And a "[language.rust]" section that does not set "threshold"
    When the operator runs crap4rs analysis in that directory
    Then the effective threshold is 20.0

  @unwired
  Scenario: crap4ts reads the typescript section from the same shared file
    # tracked: crap-rs#169 — verified via crates/crap4ts/tests integration (crap4ts unrunnable in this harness)
    Given a "crap.toml" with a shared top-level "threshold = 20.0"
    And a "[language.typescript]" section with "threshold = 25.0"
    When the operator runs crap4ts analysis in that directory
    Then the effective threshold is 25.0
    And the rust section is ignored by crap4ts

  # ── Output title / subtitle (#348, replaces #336 comment-preamble) ──

  @unwired
  Scenario: output title and subtitle label the scorecard via config
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core OutputConfig parse + reporter unit tests
    Given a "crap.toml" with an "[output]" section
    And "title" set to "Acme Coverage Report"
    And "subtitle" set to "nightly build"
    When the operator runs analysis with a titled reporter
    Then the scorecard is labeled "Acme Coverage Report"
    And the scorecard subtitle reads "nightly build"

  @unwired
  Scenario: title and subtitle are optional and absent by default
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core OutputConfig default test
    Given a "crap.toml" with no "[output].title" and no "[output].subtitle"
    When the operator runs analysis
    Then the scorecard renders with its default unlabeled header
    And no title or subtitle line is emitted

  # ── JSON Schema artifact (#348) ────────────────────────────────────

  @unwired
  Scenario: a committed JSON Schema is derived from the same config type
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; build verifies via crap-core schemars schema-shape test + committed-artifact sync
    Given the config schema type
    When the JSON Schema is generated from it
    Then each documented field appears as a property with a non-empty description
    And the committed schema artifact is byte-identical to the regenerated schema

  @unwired
  Scenario: an editor honoring $schema validates a consumer's crap.toml
    # tracked: crap-rs#169 — config_schema cucumber wiring deferred; documents the editor-integration intent; build verifies the schema artifact shape, not a live editor
    Given a consumer's "crap.toml" referencing the committed JSON Schema via "$schema"
    When the consumer types an unknown top-level key
    Then the editor flags the unknown key against the schema
    And valid keys offer autocomplete from the schema's property descriptions
