Feature: --baseline delta analysis (Bundle E, issue #81)

  When investigators or CI consumers want to know whether a code change
  raised or lowered the CRAP risk profile relative to a baseline, they
  pass a previously-emitted crap4rs JSON envelope as `--baseline <path>`.
  Crap4rs computes a delta against the current analysis and emits a
  `delta` block in every reporter format. The delta is **informational
  by default** — `--delta-gate` opts in to making the delta contribute
  to exit code. `--no-fail` overrides both the threshold gate and the
  delta gate.

  The gate keystone holds: `result.passed` always reflects the
  unfiltered current analysis; `delta.summary.passed` reflects the
  delta gate. Both are truthful in JSON even when `--no-fail` forces
  exit 0.

  Background:
    Given a project with `lib.rs` containing 6 functions, 3 passing and
    3 failing, with `lcov.info` generated by `cargo llvm-cov`
    And a saved baseline JSON envelope produced by an earlier
    `crap4rs --format json` invocation against the same source

  # ── Domain: FunctionChange classification ──────────────────────────

  Scenario: Identical baseline and current produces all-Modified delta
    Given the baseline JSON encodes the exact current AnalysisResult
    When `delta::compute(baseline, current)` runs
    Then every `FunctionChange` is `Modified`
    And every `score_delta` is `0.0`
    And `delta.summary.regressions` is `0`
    And `delta.summary.improvements` is `0`
    And `delta.summary.new_violations` is `0`
    And `delta.summary.passed` is `true`

  Scenario: Function present in current only is classified Added
    Given the baseline JSON does not contain function `parser::tokenize`
    And the current analysis does contain `parser::tokenize` with score 31
    When the delta is computed
    Then `parser::tokenize` is in `delta.changes` as `Added` with current.score = 31
    And `delta.summary.added` includes that function

  Scenario: Function present in baseline only is classified Removed
    Given the baseline JSON contains function `legacy::frob` with score 8
    And the current analysis does not contain `legacy::frob`
    When the delta is computed
    Then `legacy::frob` is in `delta.changes` as `Removed` with baseline.score = 8
    And `delta.summary.removed` includes that function

  Scenario: Function present in both is classified Modified
    Given baseline contains `cli::run_inner` with score 8
    And current contains `cli::run_inner` with score 24
    When the delta is computed
    Then `cli::run_inner` is in `delta.changes` as `Modified` with score_delta = 16
    And `delta.summary.regressions` includes that function
    And `delta.summary.modified` is incremented

  Scenario: Function with score_delta < 0 is counted as improvement
    Given baseline contains `parser::tokenize` with score 47
    And current contains `parser::tokenize` with score 12
    When the delta is computed
    Then `parser::tokenize` is `Modified` with score_delta = -35
    And `delta.summary.improvements` includes that function
    And `delta.summary.regressions` does not

  # ── Domain: identity matching ──────────────────────────────────────

  Scenario: Functions are matched by (file_path, qualified_name)
    Given baseline contains `src/foo.rs::module::fn_a`
    And current contains `src/foo.rs::module::fn_a`
    When the delta is computed
    Then the function is `Modified` (matched), not `Added`+`Removed`

  Scenario: Same name in different files counts as separate functions
    Given baseline contains `src/a.rs::helpers::log`
    And current contains `src/b.rs::helpers::log` (file moved, same name)
    When the delta is computed
    Then there is one `Removed` change for `src/a.rs::helpers::log`
    And one `Added` change for `src/b.rs::helpers::log`
    # Rename/move detection is a v0.3.0 follow-up

  Scenario: Same-file rename produces Add+Remove
    Given baseline contains `src/foo.rs::utils::compute_v1`
    And current contains `src/foo.rs::utils::compute_v2` (renamed)
    When the delta is computed
    Then `compute_v1` is `Removed`
    And `compute_v2` is `Added`

  # ── Domain: new_violations gate counting ───────────────────────────

  Scenario: Added function over threshold counts as new_violation
    Given threshold is 25
    And baseline does not contain `wild::beast`
    And current contains `wild::beast` with score 31
    When the delta is computed
    Then `delta.summary.new_violations` is `1`
    And `delta.summary.passed` is `false`

  Scenario: Modified function crossing from passing to failing counts as new_violation
    Given threshold is 25
    And baseline contains `cli::run_inner` with score 8 (passing)
    And current contains `cli::run_inner` with score 47 (failing)
    When the delta is computed
    Then `delta.summary.new_violations` is `1`

  Scenario: Modified function getting worse but still passing does NOT count as new_violation
    Given threshold is 25
    And baseline contains `parser::tokenize` with score 8
    And current contains `parser::tokenize` with score 20 (still passing)
    When the delta is computed
    Then `delta.summary.regressions` is `1`
    And `delta.summary.new_violations` is `0`

  Scenario: Modified function that was already failing in baseline does NOT count
    Given threshold is 25
    And baseline contains `legacy::frob` with score 47 (already failing)
    And current contains `legacy::frob` with score 60 (still failing, worse)
    When the delta is computed
    Then `delta.summary.regressions` is `1`
    And `delta.summary.new_violations` is `0`
    # Pre-existing debt isn't this PR's regression

  # ── DeltaViewSpec: filter, sort, truncate ──────────────────────────

  Scenario: Default DeltaViewSpec is filter=all, sort=score_delta desc
    When `delta::apply(&delta, DeltaViewSpec::default())` runs
    Then `view.shown` contains every `FunctionChange` in `delta.changes`
    And rows are ordered by signed `score_delta` descending (regressions first, improvements last)

  Scenario: Filter by change_kinds=[added] returns only Added
    When `delta::apply` is called with `filters.change_kinds = Some({Added})`
    Then `view.shown` contains only `Added` variants

  Scenario: Sort by current_crap descending
    When `delta::apply` is called with `sort = CurrentCrap`
    Then rows are ordered by current.score descending
    And `Removed` entries (no current score) sort last

  Scenario: Truncate by limit
    Given `delta.changes` has 10 entries
    When `delta::apply` is called with `limit = Some(3)`
    Then `view.shown.len()` is `3`
    And `view.eligible_count` is `10`
    And `view.truncated` is `true`

  # ── CLI: --baseline flag resolution ────────────────────────────────

  Scenario: --baseline flag loads JSON envelope and emits delta block
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json --format json`
    Then the JSON envelope contains a top-level `delta` key
    And `delta.summary` is present
    And `delta.spec` echoes resolved DeltaViewSpec
    And `delta.shown` is a denormalized array of FunctionChange entries

  Scenario: Without --baseline, JSON envelope omits delta key entirely
    When the operator runs `crap4rs --coverage lcov.info --format json`
    Then the JSON envelope does NOT contain a `delta` key
    And the envelope is byte-identical to today's output

  Scenario: Without --baseline, all reporters render today's output unchanged
    When the operator runs `crap4rs --coverage lcov.info --format markdown` (no --baseline)
    Then the markdown output contains the existing summary block only
    And no "Delta" section appears

  # ── CLI: gate semantics ────────────────────────────────────────────

  Scenario: --baseline alone is informational — exit code reflects only threshold gate
    Given the current analysis has 3 threshold violations (exit 1 today)
    And the baseline has 3 threshold violations (no new violations introduced)
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json`
    Then the process exits 1 (because of the threshold gate, NOT delta)
    And `delta.summary.passed` is `true`

  Scenario: --baseline alone with passing analysis exits 0 even if delta has regressions
    Given the current analysis has 0 threshold violations
    And the baseline shows the current PR introduced 2 new regressions
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json`
    Then the process exits 0
    And `delta.summary.regressions` is `2`
    And `delta.summary.passed` is `false`
    # Default behavior: delta is informational, doesn't gate

  Scenario: --delta-gate makes delta contribute to exit code
    Given the current analysis has 0 threshold violations
    And the baseline shows this PR introduced 1 new violation
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json --delta-gate`
    Then the process exits 1 (delta gate fired)
    And `delta.summary.passed` is `false`

  Scenario: --delta-gate without new violations exits 0
    Given the current analysis has 0 threshold violations
    And the baseline shows no new violations introduced
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json --delta-gate`
    Then the process exits 0
    And `delta.summary.passed` is `true`

  Scenario: --no-fail overrides --delta-gate (truth still in JSON)
    Given the current analysis is failing AND the delta has new violations
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json --delta-gate --no-fail`
    Then the process exits 0
    And `result.passed` is `false`
    And `delta.summary.passed` is `false`

  Scenario: --no-fail without --delta-gate behaves as today
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json --no-fail`
    Then the process exits 0 regardless of threshold violations
    And the delta is still surfaced informationally

  # ── CLI: shaping flags compose with delta ──────────────────────────

  Scenario: --delta-top truncates delta.shown
    Given the delta has 10 changes
    When the operator runs `crap4rs … --baseline baseline.json --delta-top 3 --format json`
    Then `delta.shown.len()` is `3`
    And `delta.eligible_count` is `10`
    And `delta.truncated` is `true`

  Scenario: --delta-sort current-crap orders by current score
    When the operator runs `crap4rs … --baseline baseline.json --delta-sort current-crap --format json`
    Then `delta.spec.sort` is `"current_crap"`
    And `delta.shown` is ordered by current.score descending

  Scenario: --delta-only filters to specified change kinds
    When the operator runs `crap4rs … --baseline baseline.json --delta-only added,modified --format json`
    Then `delta.shown` contains only `Added` and `Modified` entries
    And `Removed` entries are absent

  # ── Reporter rendering ─────────────────────────────────────────────

  Scenario: Table reporter renders Delta section under analysis table
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json` (default --format table)
    Then stdout contains the existing analysis table
    And below it a "Delta vs baseline" header
    And a per-change row table with columns: kind, path, function, baseline, current, Δ
    And a delta summary line: "+N added, M removed, K modified, R regressions, I improvements, V new violations"

  Scenario: Markdown reporter renders PR-comment scorecard
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json --format markdown`
    Then stdout contains a "## CRAP Scorecard" header
    And a Status line ("PASS" or "FAIL" per result.passed)
    And a Delta vs baseline counts block
    And tables for biggest regressions and new violations

  Scenario: CSV reporter adds change_kind column
    When the operator runs `crap4rs --coverage lcov.info --baseline baseline.json --format csv`
    Then the CSV header has 11 columns: existing 10 + `change_kind`
    And data rows include the change kind for each delta entry

  Scenario: --minimal-view does NOT suppress delta block
    When the operator runs `crap4rs … --baseline baseline.json --minimal-view --format json`
    Then `view.shown` is omitted (existing --minimal-view behavior)
    And `delta.shown` is still present (delta is the whole reason for invocation)

  # ── JSON envelope shape ────────────────────────────────────────────

  Scenario: schema_version stays at 1 (additive)
    When the operator runs `crap4rs … --baseline baseline.json --format json`
    Then `schema_version` is `1`
    And `delta` is a sibling of `result` and `view`

  Scenario: delta block contains baseline metadata
    When the operator runs `crap4rs … --baseline baseline.json --format json`
    Then `delta.baseline_tool_version` matches the baseline's tool_version
    And `delta.baseline_timestamp` matches the baseline's timestamp
    And `delta.baseline_ref` is `null` (reserved for future --baseline-ref flag)

  Scenario: delta block propagates baseline diagnostics
    Given the baseline JSON includes a `diagnostics` field
    When the operator runs `crap4rs … --baseline baseline.json --format json`
    Then `delta.baseline_diagnostics` reflects the baseline's diagnostics

  # ── Validation errors ──────────────────────────────────────────────

  Scenario: --baseline with non-existent path exits 2
    When the operator runs `crap4rs --coverage lcov.info --baseline /nonexistent.json`
    Then the process exits 2
    And stderr contains "baseline file not found"

  Scenario: --baseline with malformed JSON exits 2
    Given `bad.json` is not valid JSON
    When the operator runs `crap4rs --coverage lcov.info --baseline bad.json`
    Then the process exits 2
    And stderr contains "failed to parse baseline JSON"

  Scenario: --baseline with mismatched schema_version exits 2
    Given `future.json` declares `schema_version: 2`
    When the operator runs `crap4rs --coverage lcov.info --baseline future.json`
    Then the process exits 2
    And stderr contains "unsupported baseline schema_version"

  Scenario: --delta-only with unknown kind exits 2
    When the operator runs `crap4rs … --baseline baseline.json --delta-only nonsense`
    Then the process exits 2
    And stderr contains "invalid value 'nonsense' for '--delta-only'"

  Scenario: --delta-sort with unknown key exits 2
    When the operator runs `crap4rs … --baseline baseline.json --delta-sort nonsense`
    Then the process exits 2
    And stderr contains "invalid value 'nonsense' for '--delta-sort'"

  Scenario: --delta-top with negative value exits 2
    When the operator runs `crap4rs … --baseline baseline.json --delta-top -5`
    Then the process exits 2
    And stderr contains "invalid value '-5' for '--delta-top'"

  # ── Help discoverability ───────────────────────────────────────────

  Scenario: --help advertises --baseline and --delta-gate
    When the operator runs `crap4rs --help`
    Then stdout mentions "--baseline"
    And stdout mentions "--delta-gate"
    And stdout shows a basic delta example
    And stdout shows the scorecard example with `--format markdown`

  # ── Walking-skeleton invariants (property-tested) ──────────────────

  Scenario: Identity invariant — compute(r, r) yields all-Modified, all zero
    Given any `AnalysisResult` r
    When `delta::compute(r.clone(), r)` runs
    Then every change is `Modified` with `score_delta == 0.0`
    And `delta.summary.regressions == 0`
    And `delta.summary.new_violations == 0`

  Scenario: Containment invariant — view.shown is a subset of delta.changes
    Given any `AnalysisDelta` and any `DeltaViewSpec`
    When `delta::apply(&delta, spec)` runs
    Then every entry in `view.shown` exists in `delta.changes`
    And `view.eligible_count <= delta.changes.len()`

  Scenario: Gate orthogonality — result.passed is unaffected by --baseline
    Given any current analysis r
    When the operator runs `crap4rs … --baseline X --format json` and `crap4rs … --format json` (without baseline)
    Then `result` (and `result.passed`) is byte-identical between the two runs
